[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/discord-bot"
  status = 200